#!/usr/bin/bash
alpha="$1"
[[ -d tmp-gravity-wave-$alpha ]] && rm -rf tmp-gravity-wave-$alpha
[[ ! -d tmp-gravity-wave-$alpha ]] && mkdir tmp-gravity-wave-$alpha
python examples/plot_timelapsed_icon_multifiles_on_plate_carree_projection.py\
    tmp-gravity-wave-$alpha --save-animation\
    --netcdf-response-var-file-path /work/bm1233/m300685/UAICON/modes/inverse/GWS_202212*0063.nc  /work/bm1233/m300685/UAICON/modes/inverse/GWS_202212*0064.nc \
    --alpha "$alpha"
	
