#!/usr/bin/bash
# @brief Run T. Doeffel visualization script
# @note TODO: probably should be slurm script... at the momnet ignoring
#             if running in sallooc mode
set -eux

DEFAULT_DEBUG=""
DEBUG="${DEBUG:-$DEFAULT_DEBUG}"

data_dir="/work/bm1233/b383183/runs/uaicon-iap/CAIRT/R2B08_free/remapped_latlon"
output_dir="/work/bm1233/b383137/omnisuite_visualizations/tdoerffel_250km/"

# TODO: start with a single file then see how you could batch process
# for all files desired
netcdf_file="uvwtemp_3d_ML_20181215T000000Z_latlon.nc"

netcdf_file_path="${data_dir}/${netcdf_file}"
zonal_wind="u"
temporal_resolution_in_hours="1"

debug_args=""
if [[ "${DEBUG}" == "ON" ]]
then
    debug_args="-m pdb"
fi

python ${debug_args} examples/plot_timelapsed_icon_multifiles_tdoerffel_250km.py \
    --save-animation\
    --netcdf-response-var-file-path "${netcdf_file_path}"\
    --netcdf-response-var-short-name "${zonal_wind}"\
    --time-delta-in-hours-between-consecutive-files "${temporal_resolution_in_hours}"\
    --show-timestamp\
    "${output_dir}"
