#!/usr/bin/bash
# @brief Run T. Doeffel visualization script
#  TODO: probably should be slurm script... at the momnet ignoring
#             if running in sallooc mode
set -eu

DEFAULT_DEBUG=""
DEBUG="${DEBUG:-$DEFAULT_DEBUG}"

data_dir="/work/bm1233/b383183/runs/uaicon-iap/CAIRT/R2B08_free/remapped_latlon"
base_output_dir="/work/bm1233/b383137/omnisuite_visualizations/tdoerffel_250km"

# Splitting computation across two sets to stay within 24 GB interactive
# memory limit... a single file load requires ~ 2 GB RAM
netcdf_file_paths_first=""
for day in $(seq 15 21) 
do
    netcdf_file="uvwtemp_3d_ML_201812${day}T000000Z_latlon.nc"
    netcdf_file_path="${data_dir}/${netcdf_file}"
    netcdf_file_paths_first="${netcdf_file_paths_first} ${netcdf_file_path}"
done

zonal_wind="u"

debug_args=""
if [[ "${DEBUG}" == "ON" ]]
then
    debug_args="-m pdb"
fi

set -x
for level_ix in 100 150 200
do
    output_dir="${base_output_dir}/height_${level_ix}km"
    if [[ ! -d "${output_dir}" ]]
    then
        mkdir "${output_dir}"
    fi

    python ${debug_args} examples/plot_timelapsed_icon_multifiles_tdoerffel_250km.py \
        --save-animation\
        --netcdf-response-var-file-path ${netcdf_file_paths_first}\
        --netcdf-response-var-short-name "${zonal_wind}"\
        --level-ix ${level_ix} \
        -W 7680 -H 4320\
        "${output_dir}"
done 
