#!/usr/bin/bash
alpha="${1:-0.5}"
debug="$2"
if [[ $debug -eq 1 ]]
then
    pdb="-m pdb"
fi

[[ -d tmp-gravity-wave-$alpha ]] && rm -rf tmp-gravity-wave-$alpha
[[ ! -d tmp-gravity-wave-$alpha ]] && mkdir tmp-gravity-wave-$alpha
python ${pdb} examples/plot_timelapsed_icon_multifiles_on_plate_carree_projection.py\
    tmp-gravity-wave-$alpha --save-animation\
    --netcdf-response-var-file-path /work/bm1233/m300685/UAICON/modes/inverse/GWS_202212*0053.nc  /work/bm1233/m300685/UAICON/modes/inverse/GWS_202212*0054.nc \
    --alpha "$alpha"\
    --label-timestamp\
    --time-delta-in-hours-between-consecutive-files 6 \
    --timestamp-x-pos 0.942 --timestamp-y-pos 0.975
	
